Repository folkarps/F3, pull requests merged in 2019-08, with the labels that each got.

#259 Add virtual faction aliases to other components
  f/assignGear/f_assignInsignia.sqf
  f/briefing/fn_createBriefing.sqf
  f/groupMarkers/f_setLocalGroupMarkers.sqf
  f/groupMarkers/fn_groupData.sqf
Labels: S3:PR Open

#260 Contact gear fixes
  f/assignGear/f_assignGear_npr.sqf
  f/assignGear/f_assignGear_spetsnaz.sqf
  f/assignGear/f_assignInsignia.sqf
Labels: T:Bug

#262 Orbat: Marker for specialists and cargo
  f/briefing/f_orbatNotes.sqf
Labels: T:Component improvement
